-- ====================================================================
-- TAKLIM CBT - SUPABASE POSTGRESQL PRODUCTION SCHEMA
-- ====================================================================

-- 1. Table for Question Banks (Multi-Category: Afkar, Quran, etc.)
CREATE TABLE IF NOT EXISTS exam_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id VARCHAR(50) NOT NULL DEFAULT 'afkar',
  question_number INT NOT NULL,
  question_text TEXT NOT NULL,
  options JSONB NOT NULL,
  answer_key VARCHAR(5) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(category_id, question_number)
);

-- 2. Table for Final Exam Results & Candidate Submissions
CREATE TABLE IF NOT EXISTS exam_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nim VARCHAR(50) NOT NULL,
  nama VARCHAR(255) NOT NULL,
  mabna VARCHAR(100) NOT NULL,
  kategori VARCHAR(50) NOT NULL,
  kategori_name VARCHAR(100) NOT NULL,
  score INT NOT NULL,
  total_questions INT NOT NULL,
  percentage INT NOT NULL,
  tab_switches INT NOT NULL DEFAULT 0,
  duration_seconds INT NOT NULL DEFAULT 0,
  answers JSONB NOT NULL,
  submitted_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(nim, kategori)
);

-- Disable Row Level Security (RLS) so API queries can insert/select without RLS blocks
ALTER TABLE exam_questions DISABLE ROW LEVEL SECURITY;
ALTER TABLE exam_results DISABLE ROW LEVEL SECURITY;

-- Performance Indexes
CREATE INDEX IF NOT EXISTS idx_exam_results_kategori ON exam_results(kategori);
CREATE INDEX IF NOT EXISTS idx_exam_results_nim ON exam_results(nim);
CREATE INDEX IF NOT EXISTS idx_exam_questions_category ON exam_questions(category_id);
